### ISSUE TITLE
Missing category on some skins.

### ISSUE THREAD

**Issue by piyanggoon** [ByMykel/CSGO-API#100]
all.json
>     "skin-34472244_0": {
>         "id": "skin-34472244_0",
>         "skin_id": "skin-34472244",
>         "name": "★ Kukri Knife | Boreal Forest (Factory New)",
>         "weapon": {
>             "id": "weapon_knife_kukri",
>             "name": "Kukri Knife"
>         },
>         "category": {
>             "id": null,
>             "name": null
>         },

skins.json

>         "id": "skin-34472244",
>         "name": "★ Kukri Knife | Boreal Forest",
>         "description": "Used in traditional rituals, such as weddings or stabbings. It has been painted using a forest camouflage hydrographic.\\n\\n<i>The woods can be a dangerous place... never travel alone</i>",
>         "weapon": {
>             "id": "weapon_knife_kukri",
>             "name": "Kukri Knife"
>         },
>         "category": {
>             "id": null,
>             "name": null
>         },

**Comment by ByMykel** [comment]
Fixed. As I have changed the way data is updated we have to wait until CS2 is updated. If you need this to be fixed now I can force it to update.

**Comment by hackeryutu** [comment]
This one still has no category.

<img width="576" alt="image" src="https://github.com/ByMykel/CSGO-API/assets/16240260/ebeb1453-847c-46a6-b78b-b3ed47e90ff7">

**Comment by ByMykel** [comment]
@hackeryutu Open the issue again if you find the name of the category that has the zeus
