### ISSUE TITLE
Missing graffiti colors and their images

### ISSUE THREAD

**Issue by say1j** [ByMykel/CSGO-API#101]
Many graffiti have their own colors, but they are all grouped into one graffiti in [graffiti.json](https://github.com/ByMykel/CSGO-API/blob/main/public/api/en/graffiti.json)

![image](https://github.com/ByMykel/CSGO-API/assets/31889581/5b50a9a9-fef1-4f29-a1d6-05124734e830)

```
    {
        "id": "graffiti-1704",
        "name": "Sealed Graffiti | Tilt",
        "description": "This is a sealed container of a graffiti pattern. Once this graffiti pattern is unsealed, it will provide you with enough charges to apply the graffiti pattern <b>50</b> times to the in-game world.",
        "rarity": {
            "id": "rarity_common",
            "name": "Base Grade",
            "color": "#b0c3d9"
        },
        "crates": [],
        "image": "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/stickers/default/emo_angry_png.png"
    }
```

Is it possible to add parsing of all possible graffiti?

**Comment by piyanggoon** [comment]
#35 same issue?

**Comment by piyanggoon** [comment]
> > #35 same issue?
> 
> Yeah, but now we have the cs2 release, it's worth looking at the available data in the game files again for it

i will looking for it.
