### ISSUE TITLE
Different images for different wears

### ISSUE THREAD

**Issue by HermesDE** [ByMykel/CSGO-API#103]
Is it somehow possible to get an image for every possible wear? Currently every skin in skins.json only has one image.

**Comment by ByMykel** [comment]
hmm without scapping I don't thing so. The game files have 3 images per skin:


| light | medium | heavy |
|----------|----------|----------|
| ![image](https://github.com/ByMykel/CSGO-API/assets/38622893/4e45e831-0be5-4578-a7c1-3d9e7fb1a3e5) | ![image](https://github.com/ByMykel/CSGO-API/assets/38622893/48a97e4d-3d1a-401a-b634-61e3a02192bd) | ![image](https://github.com/ByMykel/CSGO-API/assets/38622893/11a7e3ac-40b5-4c64-b911-aab9f39c60c5) |

This is the most I can try to do.

If this solutions is enough for you, you can take any skin image and change the substring `_light_` for one of the words in the table.

```json
{
    "id": "skin-65604",
    "name": "Desert Eagle | Urban DDPAT",
    "image": "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/weapon_deagle_aa_flames_light_png.png"
}
```

**Comment by ByMykel** [comment]
I have made some changes in [skins_not_grouped.json](https://bymykel.github.io/CSGO-API/api/en/skins_not_grouped.json) to use also de medium and heavy image for skins.

You can check it [live here](https://bymykel.github.io/counter-strike-items/#/skins)

**Comment by WhoisUnknown** [comment]
Is this selection of images approximate or exact?

**Comment by HermesDE** [comment]
> hmm without scapping I don't thing so. The game files have 3 images per skin:
> 
> light	medium	heavy
> ![image](https://private-user-images.githubusercontent.com/38622893/313452439-4e45e831-0be5-4578-a7c1-3d9e7fb1a3e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzMyMjksIm5iZiI6MTcxMDY3MjkyOSwicGF0aCI6Ii8zODYyMjg5My8zMTM0NTI0MzktNGU0NWU4MzEtMGJlNS00NTc4LWE3YzEtM2Q5ZTdmYjFhM2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwNTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOWUwYWIxY2RhMWM5ZGUyMjEzODc5ZDM3YjA0M2JjMThkYjA4NDQyNTgyYjlmZmE5YTlkN2VhY2Q2NzA2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yv6Yq02q97lCU5Pbbem8GL_wLH7mXfBSOyzrq3KPWo4)	![image](https://private-user-images.githubusercontent.com/38622893/313452490-48a97e4d-3d1a-401a-b634-61e3a02192bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzMyMjksIm5iZiI6MTcxMDY3MjkyOSwicGF0aCI6Ii8zODYyMjg5My8zMTM0NTI0OTAtNDhhOTdlNGQtM2QxYS00MDFhLWI2MzQtNjFlM2EwMjE5MmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwNTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZTMzZWZkM2Q4MTExY2JjZGRiYmM4ODc2ZTVkMDVhNWNkOGI5YmUwNzNiMGI4ZWM5MDc0ODBmZDI4MWVjODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XuISNYq8VkPmZIqg7Andb_6BcupD2VYWApPUDoT8Ock)	![image](https://private-user-images.githubusercontent.com/38622893/313452494-11a7e3ac-40b5-4c64-b911-aab9f39c60c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzMyMjksIm5iZiI6MTcxMDY3MjkyOSwicGF0aCI6Ii8zODYyMjg5My8zMTM0NTI0OTQtMTFhN2UzYWMtNDBiNS00YzY0LWI5MTEtYWFiOWYzOWM2MGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwNTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZTA2ZjZjM2M0ZmI3ZGVlODMzZDc5ZWI5Y2RhOTY2NGY0ZWE4YjQ2YmJhNGY3ODk4NDJlZjc1MTFiZWZlYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1hUIhhkybBDa6FuW6EIidiPW90J4JZl16uZlU2F0b9M)
> This is the most I can try to do.
> 
> If this solutions is enough for you, you can take any skin image and change the substring `_light_` for one of the words in the table.
> 
> ```json
> {
>     "id": "skin-65604",
>     "name": "Desert Eagle | Urban DDPAT",
>     "image": "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/weapon_deagle_aa_flames_light_png.png"
> }
> ```

Thank you for the fast reply. Good to know that with the substring but its not quite what im looking for. Best thing would be something where I can put in a float and it gives me the appropriate image. Like the screenshot tools some marketplaces have. I would even build an API like that by myself but I dont know how to start.

**Comment by ByMykel** [comment]
> > hmm without scapping I don't thing so. The game files have 3 images per skin:
> > light	medium	heavy
> > ![image](https://private-user-images.githubusercontent.com/38622893/313452439-4e45e831-0be5-4578-a7c1-3d9e7fb1a3e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzMyMjksIm5iZiI6MTcxMDY3MjkyOSwicGF0aCI6Ii8zODYyMjg5My8zMTM0NTI0MzktNGU0NWU4MzEtMGJlNS00NTc4LWE3YzEtM2Q5ZTdmYjFhM2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwNTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOWUwYWIxY2RhMWM5ZGUyMjEzODc5ZDM3YjA0M2JjMThkYjA4NDQyNTgyYjlmZmE5YTlkN2VhY2Q2NzA2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yv6Yq02q97lCU5Pbbem8GL_wLH7mXfBSOyzrq3KPWo4)	![image](https://private-user-images.githubusercontent.com/38622893/313452490-48a97e4d-3d1a-401a-b634-61e3a02192bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzMyMjksIm5iZiI6MTcxMDY3MjkyOSwicGF0aCI6Ii8zODYyMjg5My8zMTM0NTI0OTAtNDhhOTdlNGQtM2QxYS00MDFhLWI2MzQtNjFlM2EwMjE5MmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwNTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZTMzZWZkM2Q4MTExY2JjZGRiYmM4ODc2ZTVkMDVhNWNkOGI5YmUwNzNiMGI4ZWM5MDc0ODBmZDI4MWVjODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XuISNYq8VkPmZIqg7Andb_6BcupD2VYWApPUDoT8Ock)	![image](https://private-user-images.githubusercontent.com/38622893/313452494-11a7e3ac-40b5-4c64-b911-aab9f39c60c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzMyMjksIm5iZiI6MTcxMDY3MjkyOSwicGF0aCI6Ii8zODYyMjg5My8zMTM0NTI0OTQtMTFhN2UzYWMtNDBiNS00YzY0LWI5MTEtYWFiOWYzOWM2MGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwNTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZTA2ZjZjM2M0ZmI3ZGVlODMzZDc5ZWI5Y2RhOTY2NGY0ZWE4YjQ2YmJhNGY3ODk4NDJlZjc1MTFiZWZlYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1hUIhhkybBDa6FuW6EIidiPW90J4JZl16uZlU2F0b9M)
> > This is the most I can try to do.
> > If this solutions is enough for you, you can take any skin image and change the substring `_light_` for one of the words in the table.
> > ```json
> > {
> >     "id": "skin-65604",
> >     "name": "Desert Eagle | Urban DDPAT",
> >     "image": "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/weapon_deagle_aa_flames_light_png.png"
> > }
> > ```
> 
> Thank you for the fast reply. Good to know that with the substring but its not quite what im looking for. Best thing would be something where I can put in a float and it gives me the appropriate image. Like the screenshot tools some marketplaces have. I would even build an API like that by myself but I dont know how to start.

ah got it. Yeah that is a little bit harder to do and I don't know how to do that. The only thing I know about screenshot tool for skins is [this repo](https://github.com/andreas-mausch/csgo-skinscreenshot) that I saw a time ago, maybe it can help you to start.

**Comment by ByMykel** [comment]
> Is this selection of images approximate or exact?

I just set FN and MW to light, FT and WW to medium and BS to heavy. Not really sure if this is correct, let me know if you know the correct version.
