### ISSUE TITLE
Incorrect name on stickers, agents...

### ISSUE THREAD

**Issue by piyanggoon** [ByMykel/CSGO-API#106]
Some items have double space on name "  |"
 
example.

> Ground Rebel  | Elite Crew
> Sticker | Ninjas in Pyjamas  | Katowice 2015
> Sticker | PENTA Sports  | Katowice 2015

**Comment by ByMykel** [comment]
I am checking this and I am not able to see were is the error. I have checked the stcikers names in the SCM and they are the same.

**Comment by ByMykel** [comment]
So this is a Valve error with the translations, isn't it?

keys exctracted from [csgo_english.json](https://github.com/ByMykel/counter-strike-file-tracker/blob/main/static/csgo_english.json):

```json
"CSGO_CustomPlayer_tm_leet_variantg": "Ground Rebel  | Elite Crew",
"StickerKit_eslkatowice2015_ninjasinpyjamas": "Ninjas in Pyjamas  | Katowice 2015",
"StickerKit_eslkatowice2015_pentasports": "PENTA Sports  | Katowice 2015",
```

**Comment by piyanggoon** [comment]
If SCM has double space, maybe we should use double space in 'hash_name' and replace spaces in 'name'.

**Comment by piyanggoon** [comment]
> Trade market items have hash_name with double space i.g. [https://steamcommunity.com/market/search/render/?query=Ground%20Rebel%20%20|%20Elite%20Crew&start=0&count=10&search_descriptions=0&sort_column=price&sort_dir=asc&appid=730&norender=1](https://steamcommunity.com/market/search/render/?query=Ground%20Rebel%20%20%7C%20Elite%20Crew&start=0&count=10&search_descriptions=0&sort_column=price&sort_dir=asc&appid=730&norender=1)

I don't know before have API for fetch like this.

**Comment by piyanggoon** [comment]
@ByMykel i will use this API for generate graffiti and dump to json for you. done in 1-2 hours.

**Comment by ByMykel** [comment]
> @ByMykel i will use this API for generate graffiti and dump to json for you. done in 1-2 hours.

Check also this https://github.com/ByMykel/CSGO-API/discussions/109, we can move this discussion there

**Comment by piyanggoon** [comment]
> If SCM has double space, maybe we should use double space in 'hash_name' and replace spaces in 'name'.

@ByMykel what you think?

**Comment by ByMykel** [comment]
> hash_name

We don't have hash_name in stickers and I don't see the problem on leaving 2 spaces in the name. 

Also in SCM they have also 2 spaces but the html only renders one.

![image](https://github.com/ByMykel/CSGO-API/assets/38622893/b8f1a7ab-ee11-4351-8042-329ad3932426)
