### ISSUE TITLE
2 Sticker have duplicated name.

### ISSUE THREAD

**Issue by piyanggoon** [ByMykel/CSGO-API#110]
> Sticker | Mirage (Gold) (sticker-1692, sticker-7889)
> Sticker | Overpass (Gold) (sticker-1694, sticker-7890)

Have CS:GO, CS2 version for image.

**Comment by ByMykel** [comment]
Checking some souvenir like the `Souvenir M249 | Contrast Spray (Factory New)` they are using the CSGO sticker version

![image](https://github.com/ByMykel/CSGO-API/assets/38622893/17ef30bf-f555-4f92-ab0a-c8a8063e0d64)

steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20M4720404381197119726A34227420378D2459122223597230590

Maybe they will use the CS2 version for this actual major and maintain both versions?

**Comment by piyanggoon** [comment]
> https://steamcommunity.com/market/listings/730/Souvenir%20M249%20%7C%20Contrast%20Spray%20%28Factory%20New%29

Check on SCM for the "Sticker | Mirage (Gold)" picture, it appears to be using the CS2 version.

**Comment by piyanggoon** [comment]
I think having both versions is fine because many sites use in-game data for fetching stickers on skins/agents and use "sticker_id" during inspection for matching, not the name.
