### ISSUE TITLE
"skin-vanilla-*" missing "skin_id" on all.json

### ISSUE THREAD

**Issue by piyanggoon** [ByMykel/CSGO-API#113]
All items 'id' starting with 'skin-x' should have a 'skin_id' in all.json

Why? For easier parsing into the database to establish relations.

**Comment by piyanggoon** [comment]
And 'skin-vanilla-x_st' items are missing descriptions, crates, collections, similar to 'skin-vanilla-x'.

**Comment by ByMykel** [comment]
Check it now, I've added the skin_id.
