### ISSUE TITLE
Vanilla knives are missing float values

### ISSUE THREAD

**Issue by Luksch187** [ByMykel/CSGO-API#114]
Hey, I noticed that the vanilla knives don't have float values.

![image](https://github.com/ByMykel/CSGO-API/assets/88943096/09998332-fb66-45c0-8087-864b394f25b9)

But they have a float min and float max as every other skin does.

Is this a problem in the items_game.txt where the information is pulled from or can it be fixed?

**Comment by ByMykel** [comment]
I think vanilla knives don't have a float value. These vanilla knives are not in `items_game.txt` or at least I have not seen them, I am just hardcoding them.

Check other sites like these two:
https://csgostash.com/skin/1600/Kukri-Knife-Vanilla
https://wiki.cs.money/weapons/kukri-knife

**Comment by Luksch187** [comment]
https://csgoskins.gg/items/kukri-knife-vanilla/stattrak
https://www.reddit.com/r/GlobalOffensiveTrade/comments/3resvg/discussion_do_vanilla_knives_have_floats_or_does/

They have float borders, it's just not relevant, they look the same even with different float values.
I dont know, you might want to add it

**Comment by ByMykel** [comment]
> https://csgoskins.gg/items/kukri-knife-vanilla/stattrak https://www.reddit.com/r/GlobalOffensiveTrade/comments/3resvg/discussion_do_vanilla_knives_have_floats_or_does/
> 
> They have float borders, it's just not relevant, they look the same even with different float values. I dont know, you might want to add it

Interesting, so they have a float but is not relevant at all. I rather not to add it as long as is not requested a lot in this issues.

**Comment by Luksch187** [comment]
Hm, ok. I would appreciate it, I can also help you with researching

**Comment by ByMykel** [comment]
If you want to implement it, go ahead.

Here you have hardcoded all the knives:
https://github.com/ByMykel/CSGO-API/blob/main/utils/index.js#L67-L168

You can add there the `min_float` and `max_float` of every knife.

Then you go to `skins.js` and add the `min_float` and `max_float`:
https://github.com/ByMykel/CSGO-API/blob/main/services/skins.js#L174-L208

Then you to do the same in `skinsNotGrouped.js`:
https://github.com/ByMykel/CSGO-API/blob/main/services/skinsNotGrouped.js#L232-L270

The changes should be applied to these endpoints:

https://bymykel.github.io/CSGO-API/api/en/skins.json
https://bymykel.github.io/CSGO-API/api/en/skins_not_grouped.json

**Comment by piyanggoon** [comment]
I don't think we should include float min and max values for vanilla skins because in this parser, float refers to exterior (FN, MW, FT, WW, BS). On the marketplace, we don't want to use float for any relation.

**Comment by ByMykel** [comment]
> I don't think we should include float min and max values for vanilla skins because in this parser, float refers to exterior (FN, MW, FT, WW, BS). On the marketplace, we don't want to use float for any relation.

Yeah, I kind of thought the same.

I'am closing this issue for now. If someone has a strong argument we can re-open this.
