### ISSUE TITLE
Items game and csgo_english

### ISSUE THREAD

**Issue by AlberTajuelo** [ByMykel/CSGO-API#115]
> All data are retrieved from [items_game.txt](https://github.com/SteamDatabase/GameTracking-CSGO/blob/master/csgo/scripts/items/items_game.txt) and [csgo_english.txt](https://github.com/SteamDatabase/GameTracking-CSGO/blob/master/csgo/resource/csgo_english.txt). These files use Valve's KeyValue text file format and have to be parsed with [vdf-parser](https://github.com/p0358/vdf-parser).

Where do you found these files in CS2 folder? I searched but it's 404 in the GameTracking-CSGO repository and I have CS2 installed and I don't found these files. Its inside a vdf?

**Comment by ByMykel** [comment]
Hi, the docs and the README are outdated. You can find [items_game.txt](https://github.com/ByMykel/counter-strike-file-tracker/blob/main/static/items_game.json) and all the languages files here https://github.com/ByMykel/counter-strike-file-tracker/tree/main/static

**Comment by AlberTajuelo** [comment]
Thanks a lot!!
