### ISSUE TITLE
Incorrect market hash name for Music kit

### ISSUE THREAD

**Issue by WhoisUnknown** [ByMykel/CSGO-API#117]
Problematic subject: Music Kit | TWERL, Ekko & Sidetrack, Under Bright Lights. But maybe some more 

Steam market hash names:
https://steamcommunity.com/market/search/render/?query=Music%20Kit%20%7C%20TWERL%20and%20Ekko&start=0&count=10&search_descriptions=0&sort_column=price&sort_dir=asc&norender=1&l=en

Data hash names:
https://bymykel.github.io/CSGO-API/api/en/music_kits.json

<img width="1211" alt="image" src="https://github.com/ByMykel/CSGO-API/assets/36919008/e0c18080-a0d2-4557-b65c-8b38e0218a07">

**Comment by ByMykel** [comment]
I have found 3 with wrong market_hash_name. Should be fixed now.
