### ISSUE TITLE
Graffiti colors missing in the response even tough CDN's for them exist

### ISSUE THREAD

**Issue by sztywnygit** [ByMykel/CSGO-API#121]
Hi, I've noticed that the graffiti **King Me (Battle Green)** is missing some of it's available color tints in the response even though these are available on your cdn. Response contains the following tints:

- Battle Green - Tint id: 7
- Jungle Green - Tint id: 8
- Frog Green - Tint id: 9
- Cash Green - Tint id: 10
- Wire Blue - Tint id: 11
- Monarch Blue - Tint id: 12
- SWAT Blue - Tint id: 13
- Violent Violet - Tint id: 14
- Monster Purple - Tint id: 15
- Bazooka Pink - Tint id: 16
- Princess Pink - Tint id: 17
- War Pig Pink - Tint id: 18
- Shark White - Tint id: 19

Looking at for example Battle Green cdn: `raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/stickers/default/crown_7_png.png`
We see that 7 corresponds to the tint id. We can change that to any value from 1 - 6 and will be able to get the image for the missing tints:

- Brick Red - Tint id: 1
- Blood Red - Tint id: 2
- Tiger Orange - Tint id: 3
- Dust Brown - Tint id: 4
- Desert Amber - Tint id: 5
- Tracer Yellow - Tint id: 6

Of course with this knowledge I can easily work this around but it would be nice if this was inside the response. Not sure if there are any more like this, just letting you know :)

**Comment by ByMykel** [comment]
Hi, you are right. All the graffiti tints were done manually, so there could be more errors like this. Additionally, some graffiti might not have all the tints because the wiki I used may not be updated
