### ISSUE TITLE
[REQ] Models for Crates

### ISSUE THREAD

**Issue by K4ryuu** [ByMykel/CSGO-API#127]
Greetings,
Could you please add the model path for crates to the api? I would really appreciate it. 

EDIT: Also maybe for agents aswell.

**Comment by ByMykel** [comment]
Hi what is a model path?

**Comment by K4ryuu** [comment]
![CleanShot 2024-10-06 at 15 16 12@2x](https://github.com/user-attachments/assets/e0b1caed-b82d-4392-9437-a2802cccf861)
![CleanShot 2024-10-06 at 15 16 19@2x](https://github.com/user-attachments/assets/75ade7b6-db48-444a-b444-1179976d637f)

The path of the model in game. It's also stored in the items file

**Comment by ByMykel** [comment]
you want just the path or a link that gets you the model?

**Comment by K4ryuu** [comment]
These path are enough for tons of use cases, such as applying in game to people by just the id.
This would support long-term automated update for lot of services, because no more hardcoding of model paths would be required.

**Comment by ByMykel** [comment]
I have added `model_player` as attribute to crates and agents.

Can you check if it's what you were asking for?
https://raw.githubusercontent.com/ByMykel/CSGO-API/refs/heads/main/public/api/en/crates.json
https://raw.githubusercontent.com/ByMykel/CSGO-API/refs/heads/main/public/api/en/agents.json

**Comment by K4ryuu** [comment]
Appreciate the changes!
