### ISSUE TITLE
Can rare special items be added?

### ISSUE THREAD

**Issue by roiiiu** [ByMykel/CSGO-API#13]

**Comment by ByMykel** [comment]
@roiiiu Can you elaborate more, please. 

By rare special you mean knives and gloves?

**Comment by ByMykel** [comment]
@roiiiu I can implement this in [/crates.json](https://bymykel.github.io/CSGO-API/api/en/crates.json). In an attribute called `contains_rare`, something similar to `contains`.

**Comment by roiiiu** [comment]
Thanks! That would be great.

**Comment by roiiiu** [comment]
Thanks! That would be great.

**Comment by roiiiu** [comment]
> @roiiiu I can implement this in [/crates.json](https://bymykel.github.io/CSGO-API/api/en/crates.json). In an attribute called `contains_rare`, something similar to `contains`.

Thanks! That would be great.

**Comment by ByMykel** [comment]
@roiiiu Deployed! As there are many skins I didn't check if everything is correct, so they might be some errors.
