### ISSUE TITLE
 possible improvement...

### ISSUE THREAD

**Issue by Cutcorwn** [ByMykel/CSGO-API#131]
Hello again! I'm working on a project using the API to create one similar site like CSGOSkins ,CSGOStash, and I noticed that these sites can filter skins by "Finish Style" such as Gunsmith, Custom Paint Job, Solid Color, Anodized, Airbrushed, etc.

I was looking at the code, and I'm not sure if it's possible to include this information in the API for skins.
for not finding anything in items_game.json..

Edit1:
I was also looking for a way to include the release date of the skin or in which update the skin was added, but I'm not sure if items_game.json has this information. I'm still a bit of a novice in this, but I couldn't find it there.

**Comment by ByMykel** [comment]
Hi @Cutcorwn.

>Hello again! I'm working on a project using the API to create one similar site like CSGOSkins ,CSGOStash, and I noticed that these sites can filter skins by "Finish Style" such as Gunsmith, Custom Paint Job, Solid Color, Anodized, Airbrushed, etc.

I am not sure but in [csgo_english.json](https://raw.githubusercontent.com/ByMykel/counter-strike-file-tracker/refs/heads/main/static/csgo_english.json) I have found this:

![image](https://github.com/user-attachments/assets/51774b1d-466c-457e-847a-4958c76e90a8)


Those translations could be used based on this style value in `items_game.json`:
![image](https://github.com/user-attachments/assets/66a373e1-f951-4afc-a1c3-c3c73f72c368)

I am not sure of this and don't have a lot of free time to check it.
