### ISSUE TITLE
Images for each wear for each skin

### ISSUE THREAD

**Issue by Spacerulerwill** [ByMykel/CSGO-API#132]
Is it possible to have an image for each wear for each skin. Currently there is only factory new... the game uses the different wear images in inventory icons so it must be there somewhere?

**Comment by Spacerulerwill** [comment]
> In the game files I have only seen at most 3 images.
> 
> 
> 
> image 1: FN and MW
> 
> image 2: FT and WW
> 
> image 3: BS
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/e8871325-786e-40fa-a6ec-825d73812b24)
> 
> 

Yes, could these be included in the API response? Would be really convenient for me.

**Comment by ByMykel** [comment]
> > In the game files I have only seen at most 3 images.
> > image 1: FN and MW
> > image 2: FT and WW
> > image 3: BS
> > ![image](https://private-user-images.githubusercontent.com/38622893/388014779-e8871325-786e-40fa-a6ec-825d73812b24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDI4NTEsIm5iZiI6MTczMjEwMjU1MSwicGF0aCI6Ii8zODYyMjg5My8zODgwMTQ3NzktZTg4NzEzMjUtNzg2ZS00MGZhLWE2ZWMtODI1ZDczODEyYjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDExMzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYzgzMjA3YmViODY2YTI0YTRlYzg2YjAwMWMzMjc2MzAwNmUwNjEzN2NlNzY1MGFmYTRmZjMyZTYyMzhkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8EWxUaVWeSSB3MAqZjAX7Vm-z3nNKHtUTag6xS0CwUA)
> 
> Yes, could these be included in the API response? Would be really convenient for me.

They are already included in [skins_not_grouped.json](https://bymykel.github.io/CSGO-API/api/en/skins_not_grouped.json)

**Comment by Spacerulerwill** [comment]
Awesome! Sorry to waste your time
