### ISSUE TITLE
Missing values in pins-list

### ISSUE THREAD

**Issue by K4ryuu** [ByMykel/CSGO-API#134]
Greetings,
I've collected all the pins that currently have `null` as their rarity details.

```
- collectible-4957
- collectible-4958
- collectible-4959
- collectible-4960
- collectible-4961
- collectible-4962
- collectible-4963
```

Also some of these currently has no market hash price either.
Thank you for your work ❤️

**Comment by ByMykel** [comment]
Should be fixed now. The pinks you see without market hash are not marketable.

**Comment by K4ryuu** [comment]
> Hi, should be fixed now. The pinks you see without market hash are not marketable.

Got it. Appreciate!
