### ISSUE TITLE
All M4A1 weapons in the API are incorrectly labeled as M4A4.

### ISSUE THREAD

**Issue by roiiiu** [ByMykel/CSGO-API#14]
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/11494827/236514123-091bf504-aadd-4197-b978-b06fe7dc9495.png">

**Comment by ByMykel** [comment]
@roiiiu Thank you for spotting this error. In a couple of minutes it should be deployed.

If you have any suggestion to improve this API feel free to open more issues.
