### ISSUE TITLE
Problem with languages

### ISSUE THREAD

**Issue by snqzox** [ByMykel/CSGO-API#18]
Hi ByMykel,

I would like to ask what happend to language option?
For example:
https://bymykel.github.io/CSGO-API/api/de/stickers.json
https://bymykel.github.io/CSGO-API/api/pl/stickers.json
https://bymykel.github.io/CSGO-API/api/cs/stickers.json
throws 404.

Btw, it's really usefull project, thanks for sharing 🔥

**Comment by ByMykel** [comment]
@snqzox 

My bad, I've deleted them some days ago as I thought no one used the data in some languages.

In couple of minutes you should be able to use those endpoints like always.

**Comment by ByMykel** [comment]
@snqzox done. If you have any idea to improve this API, feel free to open an issue.
