### ISSUE TITLE
Wrong rarity in cases.

### ISSUE THREAD

**Issue by roiiiu** [ByMykel/CSGO-API#19]
Hello, I have noticed that many items inside the cases have a rarity of "Industrial", which should normally not appear in cases as they are exclusive to collections and souvenir packages. Could you please investigate this issue? Thank you!

**Comment by ByMykel** [comment]
@roiiiu Can you give me some examples?

**Comment by ByMykel** [comment]
Fixed, in 10-15 minutes this will be deployed

**Comment by hackeryutu** [comment]
Awesome bro!
