### ISSUE TITLE
Skins descriptions

### ISSUE THREAD

**Issue by say1j** [ByMykel/CSGO-API#2]
skins.json descriptions not available, but available in csgo_english.txt 
and will be appreciated if you integrate language of descriptions choice

**Comment by say1j** [comment]
also there is no descriptions for vanila skins

**Comment by ByMykel** [comment]
@say1j 

> skins.json descriptions not available

I have already added it

> language of descriptions choice

Do you mean like getting the data in other language like spanish, russian, etc?

> vanila skins

Do you mean default weapons that don't any skin?

**Comment by say1j** [comment]
yes and yes
added some info as on screenshot
there is for vanila item and for paintkit
also added collection name
added all languages support too
![image](https://user-images.githubusercontent.com/31889581/177019045-795315bb-395b-4451-bf8c-69a54af3bb1b.png)

**Comment by ByMykel** [comment]
Tomorrow I will add translated data for this contries:
```
[
  "brazilian",
  "bulgarian",
  "czech",
  "danish",
  "dutch",
  "english",
  "finnish",
  "french",
  "german",
  "greek",
  "hungarian",
  "italian",
  "japanese",
  "korean",
  "norwegian",
  "pirate",
  "polish",
  "portuguese",
  "romanian",
  "russian",
  "schinese",
  "spanish",
  "swedish",
  "tchinese",
  "thai",
  "turkish",
  "ukrainian",
]
```

**Comment by say1j** [comment]
ty and there is conflict on translated_name on some languages
add ?. to param set

**Comment by say1j** [comment]
like shown
![image](https://user-images.githubusercontent.com/31889581/177019243-e56a39ec-2f91-4b13-91dc-39bd59d78772.png)

**Comment by ByMykel** [comment]
Yeah, I have changed that because it fails in other languages. I will use different way to filter items.

**Comment by say1j** [comment]
okay, got u

**Comment by ByMykel** [comment]
Did you find any other mistake or do you have any other suggestion?

**Comment by say1j** [comment]
will be perfect if by somehow add stattrak_available
and array of possible market_names to skins
to be able join descriptions by full item name
for ex: obj['AK-47 | Redline (Field-Tested)'][lang].collection

**Comment by say1j** [comment]
so mb better to add array of possible exteriors and stattrak_available for it
not full names
if its hard for you i can resolve by myself, just some tips

**Comment by ByMykel** [comment]
> for ex: obj['AK-47 | Redline (Field-Tested)'][lang].collection

About this you can fetch  `https://bymykel.github.io/CSGO-API/api/all.json` and search for obj['skin-459880'].collection, if you want to search by name you would have to map that object as you desire.



> will be perfect if by somehow add stattrak_available

I think almost all the skins in skins.json can have stattrak, do you have any example of skin that doesn't have stattrak?



> and array of possible market_names to skins

I will add it.

**Comment by say1j** [comment]
awp dragon lore

**Comment by say1j** [comment]
P2000 | Amber Fade (Factory New)
P2000 | Chainmail (Factory New)
P250 | Bengal Tiger (Battle-Scarred)
P250 | Bone Mask (Battle-Scarred)
actually there is a lot

**Comment by ByMykel** [comment]
@say1j I have added more languages and stattrak attribute to the skins. 

About the collection name I can find the collection for all the weapons but knives and gloves, so I will add this when I figured out how to get the collection name of all skins.

**Comment by say1j** [comment]
oh nice, is there is any way to parse this data from files for each type of weapon?
because its can be updated any day and fill manully its a bad idea
magazine capasity
rate of fire
movement speed with gun
kill reward
reload time and etc
probably u saw it somewhere if u working with game files

**Comment by say1j** [comment]
found it in items_game
its example for eagle
![image](https://user-images.githubusercontent.com/31889581/177041464-329d4636-3d69-4fb1-87ce-dcc6a9eece2c.png)
