### ISSUE TITLE
Feature Request: SkinID in Skins.json

### ISSUE THREAD

**Issue by Lines08** [ByMykel/CSGO-API#23]
Hey, Just a little Request, could it be possible to add the SkinID's into the skins.json they are shown in the items_game.txt one example would be:

```
		"449"
		{
			"name"		"cu_poseidon"
```

which right now is saved as "skin-1050372" maybe add a extra line named "SkinID" or "paintIndex" this would help me a lot! :)

**Comment by ByMykel** [comment]
@Lines08 Deployed.
