### ISSUE TITLE
ERROR: Anubis collection

### ISSUE THREAD

**Issue by kikoribeiro** [ByMykel/CSGO-API#26]
# It is giving a 404 error
GET : https://raw.githubusercontent.com/steamdatabase/gametracking-csgo/108f1682bf7eeb1420caaf2357da88b614a7e1b0/csgo/pak01_dir/resource/flash/econ/set_icons/set_anubis.png 404

![imagem_2023-06-05_215839484](https://github.com/ByMykel/CSGO-API/assets/120732129/1195395a-0fdb-46ca-a6de-759c78e862b4)

**Comment by ByMykel** [comment]
Thanks, will try to fix it ASAP.
