### ISSUE TITLE
Skin ids don't match up and skins.json contains wrong information

### ISSUE THREAD

**Issue by schuler-ph** [ByMykel/CSGO-API#27]
I downloaded skins and cases and tried to link cases.contains.obj.id with skins.obj.id, but it already fails at the Csgo Weapon Case. In the contains_rare prop of the case, there is the bayonet fade which has the id skin-200616, but in skins.json this id is the five seven berries and cherries and bayonet fade has id skin-32768152. Also i tried to test if the rarities in cases.json and skins.json match up and from what i've seen at least the glock dragon tattoo and m4a4 faded zebra have the wrong rarities in skins.json. M4a4 faded zebra is Mil-spec, not industrial grade and glock dragon tatto is restricted not mil-spec. This is only wrong in skins.json.

**Comment by schuler-ph** [comment]
Additionally, the doppler knives all link to the bayonet doppler, not to their own skin entry.

**Comment by ByMykel** [comment]
@schuler-ph Thank you for reporting this bug. I don't use the API so there might the a lot of errors, so if you find more or you think some structure is not appropiate feel free to open an issue.

>Additionally, the doppler knives all link to the bayonet doppler, not to their own skin entry

I don't understand this one.

I would separe this issue in:

- [x] Fix id's in `crates.json`
- [ ] Fix rarities in `skins.json`
- [ ] Add vanilla knifes

I would try to fix all of this ASAP but I don't have much free time.

**Comment by schuler-ph** [comment]
@ByMykel I think I just misunderstood the Ids for the Doppler knives. So if you go to the Flip knife doppler phase 1 in the chroma case in crates.json it has the same id as just the bayonet doppler phase 1 in skins.json, despite it having its own entry and id in skins.json. If you look up the id of a flip knife doppler phase 1 from skins.json, it cannot be found in crates.json.

**Comment by ByMykel** [comment]
@schuler-ph Checking your example it seems like its fixed already.

**Comment by ByMykel** [comment]
@schuler-ph Vanilla knives added

**Comment by ByMykel** [comment]
@schuler-ph Fixed skin's rarities.
