### ISSUE TITLE
Add rarity's color

### ISSUE THREAD

**Issue by AmarSmajlovic** [ByMykel/CSGO-API#34]
It would be beneficial to have price and color information included in the skin details. Currently, these attributes are missing, which limits the usability and completeness of the repository. Adding price and color fields would greatly enhance the repository by providing users with easy access to essential information about each item.

**Comment by ByMykel** [comment]
@AmarSmajlovic  For getting the prices I recomend you https://prices.csgotrader.app/latest/prices_v6.json, to implement the prices in this API i would need to scrap the steam market periodically and that is a lot of work for something that you can already have with the last link.

When you say colors you mean the rarities color? That is something doable and also something that you could implement as you have the rarities of every skin.

**Comment by ByMykel** [comment]
I'm not sure if you meant rarities color. 

If somehow the rarity color is important reopen this issue.
