### ISSUE TITLE
Graffiti colours missing

### ISSUE THREAD

**Issue by xapolloandy** [ByMykel/CSGO-API#35]
Base Grade Graffitis all appear white, would love to have all the colours

**Comment by ByMykel** [comment]
I've been investigating this for a couple of days and I don't know how to implement this without hard-coding all the data.

For example some sprays have different colors and not all of them are the same 19 variants. I don't know how to figure out the exact colors without checking some wiki site.

If no one know some way to avoid hard-coding I think I will start adding some sprays little by little as there are too many.

**Comment by piyanggoon** [comment]
I think base on rarity if equal "rarity_common" will have 19 variants.

**Comment by ByMykel** [comment]
@piyanggoon but I still have to hardcode the different colors that one spray can have, right?

For example:

- https://wiki.cs.money/graffiti/sealed-graffiti-1g-tiger-orange has 19 colors.
- https://wiki.cs.money/graffiti/sealed-graffiti-bling-tiger-orange has 14 colors.
- https://wiki.cs.money/graffiti/sealed-graffiti-1g-tiger-orange has 16 colors.

**Comment by piyanggoon** [comment]
what about image per spray? we can use it for ref variants?

**Comment by ByMykel** [comment]
> What about image on CS2 per spray? we can use it for ref variants?

I don't think so as I don't know exactly what [images](https://github.com/ByMykel/counter-strike-image-tracker) we have I just generate the url without knowing if it will work.

But other problem is that I don't think I have all the variant's color images. I have [only the default](https://github.com/ByMykel/counter-strike-image-tracker/blob/main/static/panorama/images/econ/stickers/default/axes_crossed_png.png).

**Comment by piyanggoon** [comment]
I still think all base grade have 19 variants but on wiki maybe ref on steam market.

**Comment by piyanggoon** [comment]
example: https://wiki.cs.money/graffiti/sealed-graffiti-recoil-sg-553-wire-blue

on cs.money wiki.
![CleanShot 2567-02-22 at 00 34 40@2x](https://github.com/ByMykel/CSGO-API/assets/31122178/fa92d025-c3c5-488d-93f4-bcd4564400be)

on steam market.
![CleanShot 2567-02-22 at 00 35 23@2x](https://github.com/ByMykel/CSGO-API/assets/31122178/fd127d5f-8be0-43be-b069-2ea0e48ee605)

missing Tracer Yellow, ...

**Comment by ByMykel** [comment]
@piyanggoon Even though I don't mind to hardcode a couple of data, I still don't have the images of all colors.

**Comment by piyanggoon** [comment]
@ByMykel I think there should be a tool for fetching images and checking available items on the Steam Market to solve problems like this on futures.

**Comment by ByMykel** [comment]
I've made a small test adding `Sealed Graffiti | 1G` and `Sealed Graffiti | 200 IQ`.

https://bymykel.github.io/counter-strike-items/#/graffiti?q=1G
https://bymykel.github.io/counter-strike-items/#/graffiti?q=200+IQ

I will upload the different images to the [repo](https://github.com/ByMykel/counter-strike-image-tracker) by hand.

Will try to have it done during the week.
