### ISSUE TITLE
Incorrect crate contains

### ISSUE THREAD

**Issue by eu33-kent** [ByMykel/CSGO-API#36]
Gamma and Gamma 2 Cases contain a mix of Gamma knives and Chroma knives.

Incorrect:
- Gut Knives
- Karambits
- M9 Bayonets

**Comment by ByMykel** [comment]
Thanks for reporting this. I have fixed this and it should be deployed in a couple of minutes.

**Comment by eu33-kent** [comment]
Thanks for the fix.

It's mostly fine now I think, but I noticed that the Dopplers still need to be changed to Gamma Dopplers for those 3 knives.

**Comment by ByMykel** [comment]
You are right, I have made another change that I hope will fix this. In a couple of minutes (around 15) this should be deployed.

Again thanks for reporting and feel free to report more of this bugs/features
