### ISSUE TITLE
Use steam market_hash_name as name in Skin Endpoint

### ISSUE THREAD

**Issue by RatzeR** [ByMykel/CSGO-API#38]
Hi @ByMykel, 

first of all, this project is super nice and very helpful! Thank you for creating this API! :-)

As I played around with the data, I found that the "wears" in the Skins endpoint might be not the best solution, when the idea is to use this API as a starting point and get for example price information from a second API, as you suggested in https://github.com/ByMykel/CSGO-API/issues/34. 

The "problem" is that a lot of other services uses the market_hash_name from steam as unique identifier for a skin.
In the market_hash_name the structure of the name is something like this:

`%Stattrack% %NAME_OF_SKIN% (%WEAR%)`

It would be easier to connect third party services when your naming system would follow this structure. 
I understand that this would mean that the JSON File would grow a lot, so this is just a suggestion, as it is also possible to transform the data on "our" side, when we aggregate the data in a database.

Nevertheless I suggest to follow the market_hash_name pattern, as you do this already in the Sticker Endpoint.

**Comment by ByMykel** [comment]
>first of all, this project is super nice and very helpful! Thank you for creating this API! :-)

Thank you for opening issues suggesting things to improve this project.

>It would be easier to connect third party services when your naming system would follow this structure.
I understand that this would mean that the JSON File would grow a lot, so this is just a suggestion, as it is also possible to transform the data on "our" side, when we aggregate the data in a database.

As you mention that would make the JSON File grow a lot, [public/api/en/all.json](https://github.com/ByMykel/CSGO-API/blob/main/public/api/en/all.json) is already 6.6 MB.

My idea with `name` imitate the community market, but I run into this #32 issue that i kind of know how to solve.

I had the idea of making a separate endpoint that returs all the skins in every state (stattrak, not stattrak, FN, MW, etc) without grouping them and I think it making sense to implement it.

**Solution**
-
New endpoint `/skins_not_grouped.json` (provisional name) that would not be in [public/api/en/all.json](https://github.com/ByMykel/CSGO-API/blob/main/public/api/en/all.json) with the new attribute `market_hash_name`

What do you think @RatzeR, with this new endpoint should we group doppler and gamma doppler skins as suggested in #37 ??

**Comment by RatzeR** [comment]
I think this is a good idea! So you avoid breaking changes in the current API and also provide a new one which is aligned with the Community Market! 

Regarding the Gamma Doppler Skins:
In this new API I would suggest to go with you first suggestion:

```
{
    "phases": [
        { "phase": "Phase 1", "paint_index": 852, "image": "phase1_url"  },
        { "phase": "Phase 2"," paint_index": 853, "image": "phase2_url"  },
        { "phase": "Phase 3", "paint_index": 854, "image": "phase3_url" },
    ]
}

```
