### ISSUE TITLE
"total supply" of a crate/weapon?

### ISSUE THREAD

**Issue by KenTheWhaleGoddess** [ByMykel/CSGO-API#44]
csgo might not expose this data..

but as a buyer it's important to me, example, how many bravo crates or a specific knife exist in the wild.

don't know if this is possible but I'd appreciate this feature and I'd be happy to contribute if you find a path to do this

**Comment by RatzeR** [comment]
Hi @KenTheWhaleGoddess, 

this API will not help you by this, as the data is aggregated from the game files and not from the steam market. 

Regarding the Number of units of a specific skin you can checkout the API from https://csgoskins.gg - but this API is really expansive, but you can also check the supply for each skin on their website: 

For example:
https://csgoskins.gg/items/awp-asiimov#:~:text=With%20a%20price%20range%20between,in%20public%20CS%3AGO%20inventories.

Also all skins in storage units are not trackable. 

Same for the cases, with the exception that this website might help you to find out how many cases were opened, but not about the total supply and I also have not seen any kind of statistic regarding the total amount. 

Nevertheless, this website might help you: 
https://csgocasetracker.com/total

As far as I know are the watching the CSfloat Database to get this data (this website might also help you with the skin supply)

**Comment by KenTheWhaleGoddess** [comment]
Not sure how to use this API but thank you for the response

I'd just like to get an idea of how many operation bravo cases there are,
if some cases are impossible to get info on that is okay

thanks!
