### ISSUE TITLE
Missing Passes

### ISSUE THREAD

**Issue by metzz1** [ByMykel/CSGO-API#47]
Hello, we are currently using this API for loading some information but we noticed that Passes are missing, they have descriptions, rarity and all that.

Example: Paris 2023 Viewer Pass

Thanks

**Comment by ByMykel** [comment]
Where would you put this data, on `collectibles.json` or a new file?

**Comment by ByMykel** [comment]
I've added everything related to operation passes like in [this page](https://csgoskins.gg/categories/pass).

@metzz1  Check the new JSON and let me know if there is something that could be improved.
https://github.com/ByMykel/CSGO-API/blob/main/public/api/en/collectibles/operation/pass.json


I will fix the collectible's rarity in a couple of days.
