### ISSUE TITLE
collectible-996 missing

### ISSUE THREAD

**Issue by Tom-jm03** [ByMykel/CSGO-API#61]
Hey, the collectible-996(Global Offensive Badge) is missing from https://bymykel.github.io/CSGO-API/api/en/collections.json

Also i noticed, that the provided links [items_game.txt](https://github.com/SteamDatabase/GameTracking-CSGO/blob/master/csgo/scripts/items/items_game.txt) and [csgo_english.txt](https://github.com/SteamDatabase/GameTracking-CSGO/blob/master/csgo/resource/csgo_english.txt) are not existing anymore, i think they've changed the repository structure.

**Comment by ByMykel** [comment]
Yeah I need some free time to add the new CS2 items, I will add this one quickly cause is only one item.

Also I need time to update de README and docs. I got the items_game.txt and languages from [this repo](https://github.com/ByMykel/items_game.txt).

**Comment by Tom-jm03** [comment]
Thanks!

**Comment by ByMykel** [comment]
Deployed https://cs2-api.vercel.app/api/items?id=collectible-996

**Comment by Tom-jm03** [comment]
Do you also have different resolutions of the image? And what is the new item path? The old one was `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\scripts\items` iirc

**Comment by ByMykel** [comment]
>Do you also have different resolutions of the image?

No

>And what is the new item path? The old one was C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\scripts\items iirc

`items_game.txt` is inside `Steam/steamapps/common/Counter-Strike Global Offensive/game/csgo/pak01_dir.vpk` and the translations in `Steam/steamapps/common/Counter-Strike Global Offensive/game/csgo/resource`. I haven't found the images in game files yet.

**Comment by Tom-jm03** [comment]
Thanks. Found it.

**Comment by ByMykel** [comment]
If you find the images let me know 😅

**Comment by Tom-jm03** [comment]
I'll do. I only found the images in the .vpk file.

**Comment by ByMykel** [comment]
In what vpk file have you wound the images?

**Comment by Tom-jm03** [comment]
> In what vpk file have you wound the images?

Under `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\pak01_dir.vpk`

**Comment by ByMykel** [comment]
You are right.

With [ValveResourceFormat](https://github.com/ValveResourceFormat/ValveResourceFormat) you can export them.

decompile and export:
![image](https://github.com/ByMykel/CSGO-API/assets/38622893/6e1a5ee8-c0f2-42cf-9169-11969bf87b1f)

Image i got:
![weapon_glock_am_gamma_doppler_phase3_glock_light_large_png](https://github.com/ByMykel/CSGO-API/assets/38622893/e70c1ecc-c43d-40a3-94ae-25320438dcf2)

**Comment by Tom-jm03** [comment]
Yes. How do you automate these tasks for your github repo if i may ask?

**Comment by ByMykel** [comment]
The tool VRF has also a CLI. So you can do this:

```
C:\Users\name\Desktop\Decompiler-windows-x64\Decompiler.exe --input "D:\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\pak01_dir.vpk" --output D:\csgo_images -e "vtex_c"
```

This is an example on how to export them, the CLI should have something to also decompile them to .png.

In this [issue](https://github.com/ByMykel/CSGO-API/issues/25#issuecomment-1575187947) I explain how to get de CDN url from the image (this might not work in CS2, i haven't test it)

**Comment by Tom-jm03** [comment]
Thanks!

**Comment by ByMykel** [comment]
This is the command
