### ISSUE TITLE
Add new CS2 images

### ISSUE THREAD

**Issue by ByMykel** [ByMykel/CSGO-API#62]
For now I haven't found the new cdn images, in the steam market they still use the old CSGO ones.

Some comparisons (left old, right new):
![Captura de pantalla 2023-10-13 232346](https://github.com/ByMykel/CSGO-API/assets/38622893/b734801d-c733-4ba2-a994-f3a80904b7f9)

![Captura de pantalla 2023-10-13 232412](https://github.com/ByMykel/CSGO-API/assets/38622893/7f338572-33f9-45e1-8c75-e2d389c45262)

![Captura de pantalla 2023-10-13 232512](https://github.com/ByMykel/CSGO-API/assets/38622893/9c3565c9-3875-4f4a-8546-9b5cceeafdf8)

![Captura de pantalla 2023-10-13 232550](https://github.com/ByMykel/CSGO-API/assets/38622893/d04d2ef8-d5b2-4ef1-8d9f-726cb0643a02)

I can try to add all the images to this repository until the cdn is available.

**Comment by Tom-jm03** [comment]
Hey, do you know where the elo images are stored?
Couldn't find them 
![image](https://github.com/ByMykel/CSGO-API/assets/92334622/2118cb25-91ad-4b46-b4a8-950986e2a4ae)

**Comment by ByMykel** [comment]
@Tom-jm03  Search `premier_rating_bg_large`, is and SVG that I think is edited somehow with the correct colors.

![premier_rating_bg](https://github.com/ByMykel/CSGO-API/assets/38622893/3c218ffb-e12b-4c61-b086-73a376c65bf8)

**Comment by Tom-jm03** [comment]
thanks, but now i edited out of this picture xD
https://media.discordapp.net/attachments/1162539733835067413/1164206098677502053/chrome_nUyE5uDpwY.png?ex=65425e6b&is=652fe96b&hm=0fa711c70a88807660e6c609860cd1a33ecc3423849e562fddc771f10def7a88&=&width=719&height=358

**Comment by Tom-jm03** [comment]
Do you have discord?

**Comment by ByMykel** [comment]
Thank you, for now I don't need them.

**Comment by Lowly1337** [comment]
I decompiled all images from VPK but I was unable to find a way to get them from CDN. Old images are still available via CDN and can be obtained by just hashing decompiled PNG's.

**Comment by ByMykel** [comment]
@Lowly1337 same, I guess they haven't add them yet? If you check the community market they are using the old images.

**Comment by Lowly1337** [comment]
They provably want to improve them before adding to Steam Community, but this is last thing on their current "to do" list. There is also possibility that they will not change them at all and old images will be still in usage, because last added item (CSGO Coin) is still generated in "legacy" way. 
![image](https://github.com/ByMykel/CSGO-API/assets/62939009/72cf6b31-0400-4e20-9fbf-468523798b36)

**Comment by ByMykel** [comment]
I think they have only change the weapons, the rest like collectibles, stickers, etc, are still unchanged.
