### ISSUE TITLE
Missing StatTrak™ Music kits and tools

### ISSUE THREAD

**Issue by WhoisUnknown** [ByMykel/CSGO-API#63]
For example [StatTrak™ Music Kit | The Verkkars, EZ4ENCE ](https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20Music%20Kit%20%7C%20The%20Verkkars%2C%20EZ4ENCE)

and 

[StatTrak™ Swap Tool](https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20Swap%20Tool)

**Comment by WhoisUnknown** [comment]
You can watch my repo https://github.com/WhoisUnknown/CSGO-API/tree/main . 
I fixed some problems: 
1. Colored graffity(without image link)
2. Old souvenir items and danger zone souvenir item
3. StatTrak™ M4A4 | Howl
4. Add tools.json with swap tools, storage unit and etc.


I can't make PR because I deleted images from my repository

**Comment by ByMykel** [comment]
@WhoisUnknown thank you, will check you repo and try to implement those things.
