### ISSUE TITLE
sticker-242, collection-set-community-33 is null on name

### ISSUE THREAD

**Issue by piyanggoon** [ByMykel/CSGO-API#67]

**Comment by ByMykel** [comment]
I can't find the collection-set-community-33

**Comment by ByMykel** [comment]
Never mind I found it.

I have fixed the error with sticker-242 name's. The second error I am not sure what they are doing.

![image](https://github.com/ByMykel/CSGO-API/assets/38622893/189a4c01-4e57-4c0e-a601-523dea222332)

`set_community_33` is the same as the set_community_32 

![image](https://github.com/ByMykel/CSGO-API/assets/38622893/916e2603-b6b0-4452-9dbb-8d7ff6caab3e)
![image](https://github.com/ByMykel/CSGO-API/assets/38622893/467a310c-0c11-41a3-b7b0-20616252c9f8)

Will leave it like that and wait for new updates to clarify all this. If you have a better idea let me know.

**Comment by piyanggoon** [comment]
Maybe now want skip skin, collection have null name for parse.

**Comment by piyanggoon** [comment]
But on skin have null name have different paint_index "collection-set-community-32" vs "collection-set-community-33"

**Comment by ByMykel** [comment]
Okay, I will skip all the collections and skins that have null name to avoid errors.
