### ISSUE TITLE
Some vanilla skins have incorrect weapon name (null)

### ISSUE THREAD

**Issue by piyanggoon** [ByMykel/CSGO-API#68]
![CleanShot 2566-12-10 at 18 28 44@2x](https://github.com/ByMykel/CSGO-API/assets/31122178/12268909-214c-42e2-a23c-b19187bf7cff)

**Comment by piyanggoon** [comment]
![CleanShot 2566-12-10 at 18 30 59@2x](https://github.com/ByMykel/CSGO-API/assets/31122178/dd8d0999-8346-4708-89a4-cfb4b9cfb705)

Here list item have incorrect weapon name.

**Comment by ByMykel** [comment]
Solved. Do you need me to deploy it?
