### ISSUE TITLE
Why are there multiple skin ids

### ISSUE THREAD

**Issue by hackeryutu** [ByMykel/CSGO-API#79]
<img width="424" alt="image" src="https://github.com/ByMykel/CSGO-API/assets/16240260/c11d9557-13af-48ae-88de-2668a593e298">

AK-47 | Head Shot (Field-Tested)
StatTrak™ MP5-SD | Liquidation (Field-Tested)
MP5-SD | Liquidation (Well-Worn)
StatTrak™ MP5-SD | Liquidation (Well-Worn)
...
...

**Comment by ByMykel** [comment]
It's a bug. I will check it this weekend

**Comment by hackeryutu** [comment]
Tks~
