### ISSUE TITLE
Market hash name error

### ISSUE THREAD

**Issue by hackeryutu** [ByMykel/CSGO-API#81]
![image](https://github.com/ByMykel/CSGO-API/assets/16240260/47e23a0a-0afc-479d-ba39-840365aa2e3d)

https://steamcommunity.com/market/listings/730/Cologne%202016%20Legends%20%28Holo-Foil%29

Cologne 2016 Legends (Holo/Foil)

(Holo/Foil) ->  (Holo-Foil)

**Comment by hackeryutu** [comment]
![image](https://github.com/ByMykel/CSGO-API/assets/16240260/6b100c7b-ad0f-4bef-b153-3f35b013b018)

![image](https://github.com/ByMykel/CSGO-API/assets/16240260/9844f133-c0e9-4b5c-9009-c82623e247c9)


Sealed Graffiti | X-Axes

**Comment by hackeryutu** [comment]
![image](https://github.com/ByMykel/CSGO-API/assets/16240260/101e61e7-df47-4ac3-92ab-295dc9958988)

![image](https://github.com/ByMykel/CSGO-API/assets/16240260/0640d266-d9e3-4822-b164-9faed2032944)

Sealed Graffiti | Cloud9 | Katowice 2019

**Comment by hackeryutu** [comment]
![image](https://github.com/ByMykel/CSGO-API/assets/16240260/9abd1ce5-9f76-47b4-bafd-d86706127c0d)

![image](https://github.com/ByMykel/CSGO-API/assets/16240260/b6099968-0adf-49b2-89b2-1685b43288f1)

Sealed Graffiti | 1G

**Comment by ByMykel** [comment]
So couple of things here.

The first one

> ![image](https://private-user-images.githubusercontent.com/16240260/298272165-47e23a0a-0afc-479d-ba39-840365aa2e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDAzNjYsIm5iZiI6MTcwNTg0MDA2NiwicGF0aCI6Ii8xNjI0MDI2MC8yOTgyNzIxNjUtNDdlMjNhMGEtMGFmYy00NzlkLWJhMzktODQwMzY1YWEyZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEyMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MTM3Zjk0MDllYWRiYTQ4NmNmOTk1MmQ5YzVhODk3MDYyZTE0OGE4YzQxYjc4MTJiODVkMGIxY2Y5NGMzM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHCuCftcndLncEWCIlL9OS_BQr-9S9uQnMpJK4Hknrw)
> 
> https://steamcommunity.com/market/listings/730/Cologne%202016%20Legends%20%28Holo-Foil%29
> 
> Cologne 2016 Legends (Holo/Foil)
> 
> (Holo/Foil) -> (Holo-Foil)

I only provide the `market_hash_name` in skins, so you would need to replace (Holo/Foil) to (Holo-Foil) in you database.


> ![image](https://private-user-images.githubusercontent.com/16240260/298281685-101e61e7-df47-4ac3-92ab-295dc9958988.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDAzNjYsIm5iZiI6MTcwNTg0MDA2NiwicGF0aCI6Ii8xNjI0MDI2MC8yOTgyODE2ODUtMTAxZTYxZTctZGY0Ny00YWMzLTkyYWItMjk1ZGM5OTU4OTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEyMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZGFmY2MwZjJjZGE3MzM2M2ZiY2RhZjJlOTQyZmEyYmY0NTdiM2E0ZmM4NjE3ZWEwMzQ3YjkzZTJjYTk0ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vbVRi5nZ6vy09Yibui5UWQoyXrSnphyyBNqSywTYWQw)
> 
> ![image](https://private-user-images.githubusercontent.com/16240260/298281999-65b7b7be-3b83-499c-8eb6-0a7dd1328743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDAzNjYsIm5iZiI6MTcwNTg0MDA2NiwicGF0aCI6Ii8xNjI0MDI2MC8yOTgyODE5OTktNjViN2I3YmUtM2I4My00OTljLThlYjYtMGE3ZGQxMzI4NzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEyMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjJmODE3OWJkOGEwYWNkMzRjMTY3NmMwYTNlYTQwYzUzM2MzZDdiODhlODY5NjhhNjFlMmUwYjViMzJmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gWCfpPyIkJLOjXvv-AwY_0sUTJ4m3yzWChnVX6FXMwI)
> 
> ![image](https://private-user-images.githubusercontent.com/16240260/298281702-0640d266-d9e3-4822-b164-9faed2032944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDAzNjYsIm5iZiI6MTcwNTg0MDA2NiwicGF0aCI6Ii8xNjI0MDI2MC8yOTgyODE3MDItMDY0MGQyNjYtZDllMy00ODIyLWIxNjQtOWZhZWQyMDMyOTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEyMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZmQ5NzRjMGY4ZjYxZWY5ZmJmNWE3ZTlmYTAyZGE4ZjE1OGI4YTRjZWJmOThmZmYyNDc4YzJmODhjOTU3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bMsYYEvpFyRo44csBUCnDdVS1jQEoKWO3JikS_I4lP0)
> 
> Sealed Graffiti | Cloud9 | Katowice 2019

In Katowice 2019 the sealed graffiti were not avaliable to sell, only the people who bought the [Viewer Pass](https://steamcommunity.com/market/listings/730/Katowice%202019%20Viewer%20Pass) could use them in game:

![image](https://github.com/ByMykel/CSGO-API/assets/38622893/f245f1d2-79b2-41db-9204-50289da23675)



> ![image](https://private-user-images.githubusercontent.com/16240260/298281794-9abd1ce5-9f76-47b4-bafd-d86706127c0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDAzNjYsIm5iZiI6MTcwNTg0MDA2NiwicGF0aCI6Ii8xNjI0MDI2MC8yOTgyODE3OTQtOWFiZDFjZTUtOWY3Ni00N2I0LWJhZmQtZDg2NzA2MTI3YzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEyMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OGE3Y2QxODhhOTQ0ZWY1NDZkN2Q2NDJiYzFhNGYwYTI5MTAyZGVjOGU2NDNiM2M0Y2MwNjk4MWVhMjQ1ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w6cMvno5_O4GrRxu1fvRQJ_HFiwitSrCwNj40GwmLXE)
> 
> ![image](https://private-user-images.githubusercontent.com/16240260/298281900-f714c96a-3778-45c5-bf85-6e7775ebac2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDAzNjYsIm5iZiI6MTcwNTg0MDA2NiwicGF0aCI6Ii8xNjI0MDI2MC8yOTgyODE5MDAtZjcxNGM5NmEtMzc3OC00NWM1LWJmODUtNmU3Nzc1ZWJhYzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEyMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYWFjNmEyZWFjYjNlZjQ5NzU1M2JiN2VmNGQ5YzUyMDg2OTAyN2NkMWJkN2Y0NjFkMTA1MGJjMGQzZmM1ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7kysSujlfvSXy94vGopO7A_3Rmp4_Kp8b2SaVyrNnM)
> 
> ![image](https://private-user-images.githubusercontent.com/16240260/298281811-b6099968-0adf-49b2-89b2-1685b43288f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDAzNjYsIm5iZiI6MTcwNTg0MDA2NiwicGF0aCI6Ii8xNjI0MDI2MC8yOTgyODE4MTEtYjYwOTk5NjgtMGFkZi00OWIyLTg5YjItMTY4NWI0MzI4OGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEyMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MWVmY2YwYjA0MzJiMmQ1MTlkMTViZmNmOTNjMWU2ZjY2NGQ4NDNjMzA5ZWU4MzVmZmM0NzJiZGEwMjBlYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1cfAPUTm1QAeYcr2FSN2eF3viThLuLyTvbuvKj19-xw)
> 
> Sealed Graffiti | 1G

Related to #35

**Comment by hackeryutu** [comment]
OK！ Tks~
