### ISSUE TITLE
Gold stickers haven't been released yet in 2016

### ISSUE THREAD

**Issue by hackeryutu** [ByMykel/CSGO-API#82]
<img width="457" alt="image" src="https://github.com/ByMykel/CSGO-API/assets/16240260/ae57a0ef-1dea-4b3a-9454-9cc01a271cb5">

Sticker | WorldEdit (Gold) | MLG Columbus 2016

**Comment by ByMykel** [comment]
They were available in souvenir weapons. When I have time I will try to add some attribute the know which one are tradable. I don't promise anything.

**Comment by hackeryutu** [comment]
Thank you
