### ISSUE TITLE
About api

### ISSUE THREAD

**Issue by kerem01121** [ByMykel/CSGO-API#83]
Hello, are these apis only for photos or is there something I can integrate into my web server for the game?

**Comment by ByMykel** [comment]
This project is more focused on providing data to create your own database.

You can still use this in your projects but some files are very heavy (e.g. 4.41 MB skins.json).

**Comment by kerem01121** [comment]
what I want to tell you briefly
can I use skin sticker agent etc. in this file in my cs server if I download this project?
I have a few friends who deal with this kind of work, so I ask

**Comment by ByMykel** [comment]
hmm I don't understand the question. 

All the data you see here is extracted from game files. This is a hobby project and is not affiliated with Valve, Steam or Counter-Strike.

So you can use this project as explained in the MIT License, but I'm not sure if Valve has some restrictions in the way this data is used, I guess that if multiple sites uses similar data is somehow legal to use it.

![image](https://github.com/ByMykel/CSGO-API/assets/38622893/d766e172-a8ca-4308-8322-cb017abd0248)

**Comment by kerem01121** [comment]
![image](https://github.com/ByMykel/CSGO-API/assets/117937811/1bc6eb31-0ce6-40f2-b51c-0fb460a6b5be)
I know what you mean. 
What I mean is a little different, I guess I didn't explain it very well.
Can I use this data in the game like we used to use when we used to choose costumes, for example, when we go to the website to choose costumes, we set the costumes from there and when we enter the game, those costumes come out.
the guy in this photo is using your api to take photos, but I wanted to ask if we can take direct skins other than photos.
that was my original intention.

**Comment by ByMykel** [comment]
>the guy in this photo is using your api to take photos, but I wanted to ask if we can take direct skins other than photos.
that was my original intention

Sorry, what are direct skins?

**Comment by kerem01121** [comment]
My friend told me that these were just photographs.
what I want to ask you is that I can use the sticker agent or skins in this api directly on the weapons or characters in the game?

I may not have been able to explain myself because my English is a bit bad, I'm sorry.

**Comment by ByMykel** [comment]
Okay, so in your picture example that person is using this API to show the information, but you will need to do some extra logic to be able to change the agent/sticker/skin in you game server.


You should find a way to make that logic with data like this:

```json
{
        "id": "skin-590940_1",
        "skin_id": "skin-590940",
        "name": "AWP | Asiimov (Well-Worn)",
        "weapon": {
            "id": "weapon_awp",
            "name": "AWP"
        },
        "category": {
            "id": "csgo_inventory_weapon_category_rifles",
            "name": "Rifles"
        },
        "pattern": {
            "id": "cu_awp_asimov",
            "name": "Asiimov"
        },
        "wear": {
            "id": "SFUI_InvTooltip_Wear_Amount_3",
            "name": "Well-Worn"
        },
        "rarity": {
            "id": "rarity_ancient_weapon",
            "name": "Covert",
            "color": "#eb4b4b"
        },
        "market_hash_name": "AWP | Asiimov (Well-Worn)",
        "team": {
            "id": "both",
            "name": "Both Teams"
        },
        "image": "https://raw.githubusercontent.com/ByMykel/CSGO-API/efe25483a04a03414dea9c61d4b0e958a373cdfd/public/images/econ/default_generated/weapon_awp_cu_awp_asimov_light.png"
    },
```
