### ISSUE TITLE
The name format is different

### ISSUE THREAD

**Issue by hackeryutu** [ByMykel/CSGO-API#86]
<img width="648" alt="image" src="https://github.com/ByMykel/CSGO-API/assets/16240260/7c5fc898-2930-4839-bccd-2bc8afe18dee">

<img width="558" alt="image" src="https://github.com/ByMykel/CSGO-API/assets/16240260/924d0903-6e51-42c3-89f8-edb95a90677b">

skin-vanilla-weapon_knife_m9_bayonet_st

**Comment by ByMykel** [comment]
different fromwhat?

**Comment by ByMykel** [comment]
I think I fixed it

**Comment by hackeryutu** [comment]
"rare_special_vanilla_stattrak": "{item_name}（★ StatTrak™）",

**Comment by hackeryutu** [comment]
Thank you.
