### ISSUE TITLE
The MAC-10 | Case Hardened doesn't have stattrak

### ISSUE THREAD

**Issue by hackeryutu** [ByMykel/CSGO-API#89]
<img width="497" alt="image" src="https://github.com/ByMykel/CSGO-API/assets/16240260/d913c881-6059-4999-997d-f1590ea158b2">

![image](https://github.com/ByMykel/CSGO-API/assets/16240260/f3eaeb16-3e0a-469f-9dfa-c15889bff3f5)

**Comment by ByMykel** [comment]
Fixed.
