### ISSUE TITLE
item id mismatch

### ISSUE THREAD

**Issue by hackeryutu** [ByMykel/CSGO-API#90]
![image](https://github.com/ByMykel/CSGO-API/assets/16240260/321c4c33-6868-42b5-88fb-ed852ce83092)

![image](https://github.com/ByMykel/CSGO-API/assets/16240260/74441749-8b19-4d25-9d93-bc3877601266)

**Comment by ByMykel** [comment]
hmm are you sure is a mismatch? `collectible`'s are items like 5 Year Veteran Coin, 10 Year Veteran Coin, etc.

In your example you are confusing collectibles with collections.

**Comment by hackeryutu** [comment]
I'm sorry, I don't understand.

Is the Guardian Pin a collection?

**Comment by ByMykel** [comment]
ohh, I'm dumb. Its a typo it should be `collectible-xxxx`. I will commit a fix now.

**Comment by hackeryutu** [comment]
Thanks my bro！
