### ISSUE TITLE
Multiple images are missing

### ISSUE THREAD

**Issue by leonlarsson** [ByMykel/CSGO-API#99]
Multiple images are returning 404 from many different cases.

Examples:
From Kilowatt Case: https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/weapon_elite_dual_berettas_lethal_grin_light_png.png

From Chroma Case: https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/weapon_deagle_aq_deagle_naga_light_png.png

The above are from https://bymykel.github.io/CSGO-API/api/en/crates/cases.json

These are just some examples, there are likely hundreds.

**Comment by ByMykel** [comment]
yeah, I am trying to automate everything so I don't need to update data/images manually when there's a new update.

Somehow the script didn't downloaded all the images and I am waiting for [this workflow](https://github.com/ByMykel/counter-strike-image-tracker/actions/runs/7855862983/job/21438009970) to finish. I estimate it will finish in 3 hours and hopefully those images will work.

**Comment by ByMykel** [comment]
Should be fixed now.
